dist: xenial
env:
  global:
  - PACKERBIN_DIR=$HOME/packerbin
  - PACKER_VERSION=1.4.0
  - secure: VxHj68sRsVP74sLq0QuI8Vebi/X4dnSCKdqAvnZha7dE5x22CsJrd+zTGWXj0Vai4KGWRKDd4VK99oIErrC+8jR4S+jOq0PwoNSMXZMsrTJTGw4CimYeQbZwTd/EsnXgrzpj5pS2vSu3jBMTpvuYo39cV3hjQ2/9q8pgcBHmSBFeq775WCFwja3HyME8Lu1mcC5e9Alqy/sjD0RXeDgbnQe26Qb1MeymiRK6HpW3y0yAvDpeozFK000CzkPI2rbKsN5wCLsrrDbyMn1fQkd7QdxxMiBfm7qOvsWF9XcGWzvutRS6sKa3QU11REueA8KrAAE8C0xWnGagj6RruYcOWGniuYaMFM0fGwEV9R9DyDM8C/Brp1Tk6+QnrS93BXw0W43QuhgRHBxfoOo/v8vtzmbJJ36D0AKIna8cIuowRNEB2d2E4qqwI54L0lQg12gh8jsPhKcHgGMoHWkn0reho1BlTnyzdpBqIpT1YPc3NtivpjUieajU4PttR4jxWokPFlre7mQoITdWAr2LXANI29SlfS2+MylIVLjrorjGCaPMl1okWbhxrsqslDzjrdk8k0O9mqXEWlGaX/RmpYJK7G2kaBS5ghuesfb79U/qmfzh1PEdVmo+fip6IX7xZ61CAitqUvO6pCMV062JZQI1c6RgvlKPlwVYipsE6yIWB+I=
install:
- GO111MODULE=on GOBIN=~/.packer.d/plugins go get github.com/linode/packer-builder-linode
- "./scripts/download_packer.sh $PACKER_VERSION"
- sudo pip install ansible
script:
- "~/packerbin/packer validate -var 'linode_token=blank' image.json"
deploy:
  provider: script
  script: "~/packerbin/packer build image.json"
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: KwZ0h+FcwRA1DjkdAZjBkiDMvbh4ySXxf0XXjqrxpNz1OEs6n+MQ7JHtPtXAalCCIkA5U+8R55M+Igd3xby2CspNuuyZbfZ48OXfAWMXHsF2qJGzpw+CxdZrTXBRoczA751MU4cK61K6juiE08fzcRqpHgms0Wg8JJFFfml9qzcJWyect8U2TXtGP0fZWn4TBCL47jr3gUYFO8CwHpeJVJg5FJwzLhfWyfDW26o1y5oP5JRMp62jrckhyjUR08Zuf8bHxKOOKE6qQdZckHVwuBuWyL0V2cV4eaFXAZvlQuzScjeyeMuKtl1YaVbRsI8FckLb2NvlbxKlsRaMuri6GV02sYJdaWcF6FW2uJX4RGzXnjWUwLYmwGne2pwflCSJYdw+u1XoOx84OxKrJp1v9uM1Ih5LcCayWTRB63Ie6txbayF7nMqVyUNhYH/aC0x7zVgRTNxU5aRapeRGkmch/ZNV23pxyCC93bsxY8SreR3zLWlTcjCAkJCGpNyzLGRdNSJXRWUiK9hBEINAKPJIHd214iTyro7QiUQZnMvFgfyMthKiPSi7yRnF0+gRWPC6gzaYYVxLiIUn9ypITVmJYoM9Lzc/szoLqtvIFk/sJKiXVvWPD7AL8cFQGmvg++eEJGERfBCT4Lv/i+7Wm35+j70sUj8wpp6vJEz6gXpbnFg=
